### ISSUE TITLE
java.lang.IllegalArgumentException: state must be Initial

### ISSUE THREAD

**Issue by hiteshsarsava** [MarcinMoskala/VideoPlayView#3]
at com.marcinmoskala.videoplayview.VideoPlayView$$special$$inlined$observable$2.afterChange(Delegates.kt:58)
                                                                  at kotlin.properties.ObservableProperty.setValue(ObservableProperty.kt:36)
                                                                  at com.marcinmoskala.videoplayview.VideoPlayView.setVideoUrl(VideoPlayView.kt)
                                                                  at com.one.vipl.adapters.AdpFeeds.onBindViewHolder(AdpFeeds.java:156)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6508)
                                                                  at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6541)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5484)
                                                                  at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5750)
                                                                  at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:285)
                                                                  at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:342)
                                                                  at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:358)
                                                                  at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:365)
                                                                  at android.support.v7.widget.GapWorker.run(GapWorker.java:396)
                                                                  at android.os.Handler.handleCallback(Handler.java:751)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:154)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by MarcinMoskala** [comment]
You cannot change video url when view is already running. Library is not supporting such case. 
Although library can be improved to accept it.

**Comment by mcbenjemaa** [comment]
i'm already with this issue

**Comment by midhilajm** [comment]
Without providing solution why this issue closed?

**Comment by ImranAdil** [comment]
where is solution bro??

**Comment by iamjpsharma** [comment]
How to clear video url to play new video
